### ISSUE TITLE
Remove all keys and git push force

### ISSUE THREAD

**Issue by pedrommone** [yanmagale/twitter-event-audience#1]
You've made a commit with a lot of sensitive data, just be careful! :)

**Comment by yanmagale** [comment]
@pedrommone thanks to your report.

Its a small version to use this at other projects, so I will make a lot of changes in this project. 


I will manteined open until fix it.

**Comment by yanmagale** [comment]
I was thinking use the [dotenv](https://github.com/motdotla/dotenv) . I will make tests 👍

**Comment by yanmagale** [comment]
@pedrommone i was removed all commits and push new data to source project. Thanks to your repport.

**Comment by yanmagale** [comment]
@pedrommone i was utilized [dotenv](https://github.com/motdotla/dotenv) and using a `.env` file for put this configs :smile:
